"""esquema inicial completo

Revision ID: 257a6dc666ec
Revises: 
Create Date: 2026-08-01 20:35:45.363557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257a6dc666ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('rubric_id', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning_mode', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_units',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.String(length=1000), nullable=False),
    sa.Column('element_interactivity', sa.Integer(), nullable=False),
    sa.Column('domain_decay_rate', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learners_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_learners_name'), ['name'], unique=True)

    op.create_table('missions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('required_kus', sa.JSON(), nullable=False),
    sa.Column('optional_kus', sa.JSON(), nullable=False),
    sa.Column('terminal_threshold', sa.Float(), nullable=False),
    sa.Column('critical_kus', sa.JSON(), nullable=False),
    sa.Column('critical_threshold', sa.Float(), nullable=False),
    sa.Column('cost_weights', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('required_competences', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('evaluation_rubric', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.String(length=2000), nullable=False),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('expected_answer', sa.String(length=500), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('feedback', sa.String(length=2000), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competences',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('effective_mastery', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'ku_id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('reviewers', sa.JSON(), nullable=False),
    sa.Column('source_weight', sa.Float(), nullable=False),
    sa.Column('reviewer_agreement', sa.Float(), nullable=False),
    sa.Column('recency_factor', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_records_source_ref'), ['source_ref'], unique=False)

    op.create_table('ku_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ku_skill_links',
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ku_id', 'skill_id')
    )
    op.create_table('ku_topic_links',
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ku_id', 'topic_id')
    )
    op.create_table('study_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ku_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ku_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_materials')
    op.drop_table('ku_topic_links')
    op.drop_table('ku_skill_links')
    op.drop_table('ku_relations')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_source_ref'))

    op.drop_table('evidence_records')
    op.drop_table('competences')
    op.drop_table('challenges')
    op.drop_table('topics')
    op.drop_table('skills')
    op.drop_table('projects')
    op.drop_table('missions')
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learners_name'))
        batch_op.drop_index(batch_op.f('ix_learners_email'))

    op.drop_table('learners')
    op.drop_table('knowledge_units')
    op.drop_table('assessments')
    # ### end Alembic commands ###
