"""baseline: esquema completo com credenciais e origem de evidencia

Revision ID: 2b2a896c6912
Revises: 
Create Date: 2026-08-01 03:00:56.702394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2a896c6912'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_ref'))
        batch_op.create_index(batch_op.f('ix_evidence_records_source_ref'), ['source_ref'], unique=False)

    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text('("learner")'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('ux_learners_email'), sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ux_learners_name'))
        batch_op.create_index(batch_op.f('ix_learners_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_learners_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learners_name'))
        batch_op.drop_index(batch_op.f('ix_learners_email'))
        batch_op.create_index(batch_op.f('ux_learners_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ux_learners_email'), ['email'], unique=1, sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('("learner")'))

    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_source_ref'))
        batch_op.create_index(batch_op.f('ix_evidence_source_ref'), ['source_ref'], unique=False)

    # ### end Alembic commands ###
