"""amplia concept para 255 (slugs longos da OpenStax)

Revision ID: cb32b402af5a
Revises: 257a6dc666ec
Create Date: 2026-08-01 21:22:14.193321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb32b402af5a'
down_revision: Union[str, Sequence[str], None] = '257a6dc666ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_ref'))
        batch_op.create_index(batch_op.f('ix_evidence_records_source_ref'), ['source_ref'], unique=False)

    with op.batch_alter_table('knowledge_units', schema=None) as batch_op:
        batch_op.alter_column('concept',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text('("learner")'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('ux_learners_email'), sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ux_learners_name'))
        batch_op.create_index(batch_op.f('ix_learners_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_learners_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learners_name'))
        batch_op.drop_index(batch_op.f('ix_learners_email'))
        batch_op.create_index(batch_op.f('ux_learners_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ux_learners_email'), ['email'], unique=1, sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('("learner")'))

    with op.batch_alter_table('knowledge_units', schema=None) as batch_op:
        batch_op.alter_column('concept',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_source_ref'))
        batch_op.create_index(batch_op.f('ix_evidence_source_ref'), ['source_ref'], unique=False)

    # ### end Alembic commands ###
